version: '3'

services:
  backend:
    build:
      context: ./django
    container_name: django_container
    command: gunicorn core.wsgi
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./react
    container_name: react_container
    volumes:
      - react_build:/react/build

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "80:8080"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
    depends_on:
      - backend
      - frontend

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: 'DBus'
      MYSQL_USER: 'django-app'
      MYSQL_PASSWORD: '!bBt8-2022**'
      MYSQL_ROOT_PASSWORD: '!bBt8-2022**'
    volumes:
      - ./data/mysql/db:/var/lib/mysql
    expose:
      - 3306

volumes:
  react_build:
